---
- name: Enable git-crypt for repos
  command: git-crypt init /home/deploy/.ssh/id_rsa
  args:
    chdir: "{{ src_root }}/venv_{{ item.projectname }}/{{ item.projectname }}"
  with_items: projects
  tags:
    - server-provision
    - git-update

- name: Make vars file executable
  file: 
    path: "{{ src_root }}/venv_{{ item.projectname }}/{{ item.projectname }}/serverdeploy/vars.secure"
    state: touch 
    mode: "0764"
  with_items: projects
  register: result
  tags:
    - fresh_deploy

- name: Dump sqlcreate
  shell: "source {{ src_root }}/venv_{{ item.projectname }}/{{ item.projectname }}/serverdeploy/vars.secure && {{ src_root }}/venv_{{ item.projectname }}/bin/python {{ src_root }}/venv_{{ item.projectname }}/{{ item.projectname }}/{{ item.projectname }}/manage.py sqlcreate > /tmp/{{ item.projectname }}_sqlcreate.txt"
  args:
    executable: "/bin/bash"
  with_items: projects
  register: result
  tags:
    - fresh_deploy

- name: Fetch sqlcreate
  fetch: 
    src: "/tmp/{{ item.projectname }}_sqlcreate.txt"
    dest: /tmp/
    fail_on_missing: yes
    flat: yes
  with_items: projects
  tags:
    - fresh_deploy

# supervisorctl reread
# supervisorctl update
# supervisorctl start hello
