---
- name: Install required Python packages.
  easy_install: name={{ item }}
  with_items: python_packages

- name: Create web repo directories
  file:
    state: directory
    path: "{{ src_root }}/venv_{{ projectname }}"
  sudo: true

- name: Update web repo permissions
  file:
    path: "{{ src_root }}/venv_{{ projectname }}"
    owner: deploy
  sudo: true

- include: git-crypt-setup.yml

- name: Checkout repos
  git:
    repo: "{{ src }}"
    dest: "{{ src_root }}/venv_{{ projectname }}/{{ projectname }}"
    force: yes
    update: true
    accept_hostkey: yes
  notify: 
    - stop supervisorctl
    - restart supervisor

- name: Enable git-crypt for repos
  command: "git-crypt unlock /home/deploy/.git-crypt/{{ projectname }}"
  args:
    chdir: "{{ src_root }}/venv_{{ projectname }}/{{ projectname }}"

- name: Make vars file executable
  file:
    path: "{{ config_files_base }}/vars.secure"
    state: touch
    mode: "0700"
  register: result

- meta: flush_handlers
