---
- name: Install required Python packages.
  easy_install: name={{ item }}
  with_items: python_packages

- name: Create web repo directories
  file:
    state: directory
    path: "{{ src_root }}/venv_{{ projectname }}"
  sudo: true

- name: Update web repo permissions
  file:
    path: "{{ src_root }}/venv_{{ projectname }}"
    owner: deploy
  sudo: true

- include: git-setup.yml

- name: Checkout repos
  git:
    repo: "{{ src }}"
    dest: "{{ src_root }}/venv_{{ projectname }}/{{ projectname }}"
    force: yes
    update: true
    accept_hostkey: yes
  notify: 
    - stop supervisorctl
    - restart supervisor

- name: Copy nginx project specific configuration file
  command: cp {{ config_files_base }}/nginx-sites-enabled.conf /etc/nginx/sites-available/{{ projectname }}.conf
  sudo: true
  notify: restart nginx
  tags:
    - deploy

- name: Copy nginx offline project specific configuration file
  command: cp {{ config_files_base }}/nginx-sites-offline.conf /etc/nginx/sites-available/{{ projectname }}-offline.conf
  sudo: true
  notify: restart nginx
  tags:
    - deploy

- name: Unlink the regular nginx file for the deploy
  file: 
    path: /etc/nginx/sites-enabled/{{ projectname }}.conf
    state: absent
  sudo: true
  notify: restart nginx
  tags:
    - deploy
    - offline

- name: Link the offline nginx file for the deploy
  file: 
    src: /etc/nginx/sites-available/{{ projectname }}-offline.conf
    dest: /etc/nginx/sites-enabled/{{ projectname }}-offline.conf
    state: link
  sudo: true
  notify: restart nginx
  tags:
    - deploy
    - offline

- meta: flush_handlers

- name: Enable git-crypt for repos
  command: "git-crypt unlock /home/deploy/.git-crypt/{{ projectname }}"
  args:
    chdir: "{{ src_root }}/venv_{{ projectname }}/{{ projectname }}"

- name: Make vars file executable
  file:
    path: "{{ config_files_base }}/vars.secure"
    state: touch
    mode: "0700"
  register: result
  tags:
    - deploy

- include: rabbitmq.yml
