---
- name: Install required Python packages.
  easy_install: name={{ item }}
  with_items: python_packages

- name: Create web repo directories
  file:
    state: directory
    path: "{{ src_root }}/venv_{{ item.projectname }}"
  with_items: projects
  sudo: true

- name: Update web repo permissions
  file:
    path: "{{ src_root }}/venv_{{ item.projectname }}"
    owner: deploy
  with_items: projects
  sudo: true

- include: git-setup.yml

- name: Checkout repos
  git:
    repo: "{{ item.src }}"
    dest: "{{ src_root }}/venv_{{ item.projectname }}/{{ item.projectname }}"
    force: yes
    update: true
    accept_hostkey: yes
  notify: restart supervisor
  with_items: projects

- name: Copy nginx project specific configuration file
  command: cp {{ src_root }}/venv_{{ item.projectname }}/{{ item.projectname }}/serverdeploy/nginx-sites-enabled.conf /etc/nginx/sites-enabled/{{ item.projectname }}.conf
  with_items: projects
  sudo: true
  notify: restart nginx
  tags:
    - deploy

- name: Enable git-crypt for repos
  command: git-crypt init /home/deploy/.ssh/id_rsa
  args:
    chdir: "{{ src_root }}/venv_{{ item.projectname }}/{{ item.projectname }}"
  with_items: projects

- name: Make vars file executable
  file:
    path: "{{ src_root }}/venv_{{ item.projectname }}/{{ item.projectname }}/serverdeploy/vars.secure"
    state: touch
    mode: "0764"
  with_items: projects
  register: result
  tags:
    - deploy
