---
- name: Add New Relic Repo
  apt_repository: repo='deb http://apt.newrelic.com/debian/ newrelic non-free' state=present
  sudo: true

- name: Trust New Relic GPG key
  shell: "wget -O- https://download.newrelic.com/548C16BF.gpg | apt-key add -"
  sudo: true

- name: Update packages
  apt: upgrade=dist update_cache=yes
  sudo: true
  notify: Restart machine

- name: Install required common system packages
  apt: pkg={{ item }} state=installed
  sudo: true
  with_items: system_packages_common
  notify: Restart machine

- name: Install required role-specific system packages
  apt: pkg={{ item }} state=installed
  sudo: true
  with_items: system_packages_role_specific
  notify: Restart machine

- name: New Relic license key
  shell: "nrsysmond-config --set license_key={{ newrelic_license }}"
  sudo: true
  notify: Restart New Relic

- name: Copy visudo file
  template: src=sudoers.j2 dest=/etc/sudoers validate='visudo -cf %s'
  sudo: true
  notify: Restart machine

- name: Copy sshd config file
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config
  sudo: true
  notify: Restart machine

- name: Copy ssh key
  command: ssh-copy-id deploy@{{ inventory_hostname }}
  delegate_to: 127.0.0.1

- name: Lock down id_rsa
  file:
    path: /home/deploy/.ssh/id_rsa
    state: touch
    mode: "0600"

- meta: flush_handlers

- name: Copy host files
  template: src=hosts.j2 dest=/etc/hosts
  sudo: true
