---
- include: supervisor-setup.yml

- include: tmp-setup.yml

- include: requirements-setup.yml

- include: django-db-setup.yml

- include: static-setup.yml

- include: ../../python-app-tier/tasks/nginx-disable-offline.yml
