---
- name: Install repos requirements
  pip: requirements={{ src_root }}/venv_{{ projectname }}/{{ projectname }}/requirements.txt virtualenv={{ src_root }}/venv_{{ projectname }}
  tags:
    - deploy
