---
- name: Copy gunicorn project specific configuration file
  command: cp {{ config_files_base }}/gunicorn.conf /etc/supervisor/conf.d/{{ projectname }}.conf
  sudo: true
  notify: restart supervisor
  tags:
    - deploy
