---
- name: Install required system packages.
  apt: pkg={{ item }} state=installed update-cache=yes
  sudo: true
  with_items: system_packages_web
  tags:
    - server-provision

- name: Install required Python packages.
  easy_install: name={{ item }}
  with_items: python_packages
  tags:
    - server-provision

- name: Setup required required web dirs
  file:
    state: directory 
    path: "{{ src_root }}/venv_{{ item.projectname }}"
  with_items: projects
  sudo: true
  tags:
    - server-provision

- name: Update file permissions
  file: 
    path: "{{ src_root }}/venv_{{ item.projectname }}"
    owner: deploy
  with_items: projects
  sudo: true
  tags:
    - server-provision

- name: Remove sites-available from Nginx
  file:
    path: /etc/nginx/sites-available
    state: absent
  sudo: true
  tags: 
    - server-provision

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  sudo: true
  tags: 
    - server-provision

- name: Create nginx log directories
  file:
    path: /data/logs/web/{{ item.projectname }}
    state: directory
  with_items: projects
  sudo: true
  tags: 
    - server-provision

- name: Checkout git-crypt
  git:
    repo: "git@github.com:AGWA/git-crypt.git"
    dest: /tmp/git-crypt
    force: no
    update: true
    version: debian
    accept_hostkey: yes
  tags: 
    - server-provision

- name: Make git-crypt
  command: make
  args:
    chdir: /tmp/git-crypt
  tags: 
    - server-provision

- name: Copy git-crypt
  command: mv /tmp/git-crypt/git-crypt /usr/local/bin/git-crypt 
  sudo: true
  tags: 
    - server-provision

- name: Copy ssh key for git-crypt
  copy: src=/Users/aaron/.ssh/id_rsa dest=/home/deploy/.ssh/id_rsa
  tags:
    - server-provision
    - git-update

# Install postfix https://www.ftmon.org/blog/secure-ubuntu-server/#Setup_Email and https://sendgrid.com/docs/Integrate/Mail_Servers/postfix.html
