---
- name: Remove the offline nginx symlink
  file: 
    path: /etc/nginx/sites-enabled/{{ projectname }}-offline.conf
    state: absent
  sudo: true
  notify: restart nginx
  tags:
    - deploy

- name: Link the nginx live site
  file: 
    src: /etc/nginx/sites-available/{{ projectname }}.conf
    dest: /etc/nginx/sites-enabled/{{ projectname }}.conf
    state: link
  sudo: true
  notify: restart nginx
  tags:
    - deploy
