---
- name: Write default Nginx site
  template: src=default.j2 dest=/etc/nginx/sites-available/default
  sudo: true
  notify:
    - restart nginx

- name: Write nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  sudo: true
  notify:
    - restart nginx

- name: Create log directories
  file:
    path: /data/logs/web/{{ projectname }}
    state: directory
    owner: deploy
  sudo: true

- name: Create extra conf folder
  file:
    path: /etc/nginx/conf
    state: directory
    owner: deploy
  sudo: true
