---
- name: Install required system packages.
  apt: pkg={{ item }} state=installed update-cache=yes
  sudo: true
  with_items: system_packages_common
  tags:
    - server-provision

- name: Copy host files
  template: src=hosts.j2 dest=/etc/hosts
  sudo: true
  tags:
    - server-provision
