---
- name: Update postgresql conf
  template: src=postgresql.conf.j2 dest=/etc/postgresql/9.3/main/postgresql.conf
  sudo: true
  notify: restart postgres

- name: Update pg_hba conf
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.3/main/pg_hba.conf
  sudo: true
  sudo_user: postgres
  notify: restart postgres
