---
system_packages_common:
  - build-essential
  - git
  - libevent-dev
  - libpq-dev
  - python-dev
  - python-setuptools
  - postfix
python_packages:
  - pip
  - virtualenv
src_root: /data
projects:
  - { projectname: breedfeedlaunch, src: "git@bitbucket.org:digbymarksitconsulting/breedfeedlaunch.git", project_dir: breedfeedlaunch }
