---
- name: Deploy Breedfeed Launch
  hosts: webservers
  remote_user: deploy
  vars:
      projectname: breedfeedlaunch
      src: "git@bitbucket.org:digbymarksitconsulting/breedfeedlaunch.git"
      project_dir: breedfeedlaunch
  roles:
    - django-web-app-tier
